### ISSUE TITLE
Won't compile "unexpected concrete region in borrowck: ReStatic"

### ISSUE THREAD

**Issue by xeroc** [reef-defi/reef-chain#32]
I followed the Quick Starter guide and had to make a break at `make run` since the compile step failed with:

```
RUST_BACKTRACE=1 cargo run --manifest-path node/Cargo.toml --features with-ethereum-compatibility  -- --dev --tmp
   Compiling reef-runtime v3.0.0 (/home/xeroc/projects/Reef/reef-chain/runtime)
   Compiling sc-network-gossip v0.9.0
   Compiling sc-informant v0.9.0
   Compiling sc-offchain v3.0.0
   Compiling sc-finality-grandpa v0.9.0
   Compiling sc-chain-spec v3.0.0
   Compiling sc-finality-grandpa-rpc v0.9.0
error: failed to run custom build command for `reef-runtime v3.0.0 (/home/xeroc/projects/Reef/reef-chain/runtime)`

Caused by:
  process didn't exit successfully: `/home/xeroc/projects/Reef/reef-chain/target/debug/build/reef-runtime-f6756568918a6705/build-script-build` (exit status: 1)
  --- stdout
  Information that should be included in a bug report.
  Executing build command: "rustup" "run" "nightly" "cargo" "-Zfeatures=build_dep" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/home/xeroc/projects/Reef/reef-chain/target/debug/wbuild/reef-runtime/Cargo.toml" "--color=always" "--release"
  Using rustc version: rustc 1.56.0-nightly (b70888601 2021-07-28)


  --- stderr
  warning: flag `-Z features` has been stabilized in the 1.51 release, and is no longer necessary
    The new feature resolver is now available by specifying `resolver = "2"` in Cargo.toml.
    See https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-resolver-version-2 for more information.

     Compiling evm v0.26.0
     Compiling frame-system v3.0.0
     Compiling orml-utilities v0.4.1-dev (/home/xeroc/projects/Reef/reef-chain/orml/utilities)
     Compiling orml-traits v0.4.1-dev (/home/xeroc/projects/Reef/reef-chain/orml/traits)
     Compiling reef-primitives v0.7.3 (/home/xeroc/projects/Reef/reef-chain/primitives)
     Compiling module-evm-rpc-runtime-api v0.1.0 (/home/xeroc/projects/Reef/reef-chain/modules/evm/rpc/runtime_api)
     Compiling pallet-timestamp v3.0.0
     Compiling pallet-balances v3.0.0
     Compiling pallet-authorship v3.0.0
     Compiling pallet-transaction-payment v3.0.0
     Compiling pallet-proxy v3.0.0
     Compiling pallet-scheduler v3.0.0
     Compiling pallet-collective v3.0.0
     Compiling pallet-indices v3.0.0
     Compiling frame-executive v3.0.0
     Compiling pallet-identity v3.0.0
     Compiling pallet-randomness-collective-flip v3.0.0
  error: internal compiler error: unexpected concrete region in borrowck: ReStatic
     --> /home/xeroc/.cargo/registry/src/github.com-1ecc6299db9ec823/evm-0.26.0/src/executor/stack/state.rs:496:2
      |
  496 | /     pub fn deconstruct(
  497 | |         self
  498 | |     ) -> (impl IntoIterator<Item=Apply<impl IntoIterator<Item=(H256, H256)>>>,
  499 | |            impl IntoIterator<Item=Log>)
  500 | |     {
  501 | |         self.substate.deconstruct(self.backend)
  502 | |     }
      | |_____^
      |
      = note: delayed at compiler/rustc_mir/src/borrow_check/region_infer/opaque_types.rs:87:44

  thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1050:13
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/b70888601af92f6cdc0364abab3446e418b91d36/library/std/src/panicking.rs:515:5
     1: std::panicking::begin_panic_fmt
               at /rustc/b70888601af92f6cdc0364abab3446e418b91d36/library/std/src/panicking.rs:457:5
     2: rustc_errors::HandlerInner::flush_delayed
     3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
     4: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
     5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
     6: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
     7: rustc_span::with_source_map
     8: rustc_interface::interface::create_compiler_and_run
     9: scoped_tls::ScopedKey<T>::set
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

  error: internal compiler error: unexpected panic

  note: the compiler unexpectedly panicked. this is a bug.

  note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

  note: rustc 1.56.0-nightly (b70888601 2021-07-28) running on x86_64-unknown-linux-gnu

  note: compiler flags: -C opt-level=3 -C panic=abort -C linker-plugin-lto -C link-arg=--export-table -C link-arg=--import-memory -C link-arg=--export=__heap_base --crate-type lib

  note: some of the compiler flags provided by cargo are hidden

  query stack during panic:
  end of query stack
     Compiling pallet-sudo v3.0.0
  error: could not compile `evm`
  warning: build failed, waiting for other jobs to finish...
  error: build failed
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:53: run] Error 101
```

I am running on a more-or-less recent Archlinux. Is my rustc too new?

**Comment by xeroc** [comment]
> Is my rustc too new?

must be this. Docker builds fine

**Comment by Netherdrake** [comment]
Check `make init`, it installs the tested/stable version of rust compiler

**Comment by xeroc** [comment]
I don't see an error in `make init`:

```
➜  reef-chain git:(master) ✗ make init
rustup update stable
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2021-07-29, rust version 1.54.0 (a178d0322 2021-07-26)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
 16.7 MiB /  16.7 MiB (100 %)   6.4 MiB/s in  2s ETA:  0s
info: downloading component 'rust-std'
 21.9 MiB /  21.9 MiB (100 %)   6.4 MiB/s in  4s ETA:  0s
info: downloading component 'rustc'
 50.1 MiB /  50.1 MiB (100 %)   6.4 MiB/s in  8s ETA:  0s
info: downloading component 'rustfmt'
info: removing previous version of component 'cargo'
info: removing previous version of component 'clippy'
info: removing previous version of component 'rust-docs'
info: removing previous version of component 'rust-std'
info: removing previous version of component 'rustc'
info: removing previous version of component 'rustfmt'
info: installing component 'cargo'
info: using up to 500.0 MiB of RAM to unpack components
info: installing component 'clippy'
info: installing component 'rust-docs'
 16.7 MiB /  16.7 MiB (100 %)  10.5 MiB/s in  1s ETA:  0s
info: installing component 'rust-std'
 21.9 MiB /  21.9 MiB (100 %)  13.3 MiB/s in  1s ETA:  0s
info: installing component 'rustc'
 50.1 MiB /  50.1 MiB (100 %)  15.4 MiB/s in  4s ETA:  0s
info: installing component 'rustfmt'

  stable-x86_64-unknown-linux-gnu updated - rustc 1.54.0 (a178d0322 2021-07-26) (from rustc 1.53.0 (53cb7b09b 2021-06-17))

rustup update nightly
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2021-07-30, rust version 1.56.0-nightly (492723897 2021-07-29)
info: downloading component 'rust-std' for 'wasm32-unknown-unknown'
 13.5 MiB /  13.5 MiB (100 %)   6.4 MiB/s in  2s ETA:  0s
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
 17.1 MiB /  17.1 MiB (100 %)   6.4 MiB/s in  2s ETA:  0s
info: downloading component 'rust-std'
 22.4 MiB /  22.4 MiB (100 %)   6.2 MiB/s in 27s ETA:  0s
info: downloading component 'rustc'
 50.9 MiB /  50.9 MiB (100 %)   6.3 MiB/s in  8s ETA:  0s
info: downloading component 'rustfmt'
info: removing previous version of component 'rust-std' for 'wasm32-unknown-unknown'
info: removing previous version of component 'cargo'
info: removing previous version of component 'clippy'
info: removing previous version of component 'rust-docs'
info: removing previous version of component 'rust-std'
info: removing previous version of component 'rustc'
info: removing previous version of component 'rustfmt'
info: installing component 'rust-std' for 'wasm32-unknown-unknown'
info: using up to 500.0 MiB of RAM to unpack components
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
 17.1 MiB /  17.1 MiB (100 %)  11.2 MiB/s in  1s ETA:  0s
info: installing component 'rust-std'
 22.4 MiB /  22.4 MiB (100 %)  13.0 MiB/s in  1s ETA:  0s
info: installing component 'rustc'
 50.9 MiB /  50.9 MiB (100 %)  15.9 MiB/s in  3s ETA:  0s
info: installing component 'rustfmt'

  nightly-x86_64-unknown-linux-gnu updated - rustc 1.56.0-nightly (492723897 2021-07-29) (from rustc 1.56.0-nightly (b70888601 2021-07-28))

rustup target add wasm32-unknown-unknown --toolchain nightly
info: component 'rust-std' for target 'wasm32-unknown-unknown' is up to date
git submodule update --init --recursive
```

**Comment by Netherdrake** [comment]
Still see `rust version 1.54.0` in the log. Its probably your global default.

**Comment by xeroc** [comment]
According to the Makefile:

https://github.com/reef-defi/reef-chain/blob/716c09be41406a975db55cb188651ec3365a9e93/Makefile#L2-L6

Running
```
rustup install 1.51.0
rustup default 1.51.0
```

as per the `release` receipt in the Makefile prior to `make run` fixed it for me.
Why would `make init` install nightly while release uses a fixed released from May?

**Comment by Netherdrake** [comment]
`make init` was for developers and I didn't expect Rust to be so backwards incompatible
